default_agent: st02
agents:
  st01:
    name: st01
    entrypoint: strands_agent_file_system.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::266239926753:role/agentcorerole
      account: '266239926753'
      region: us-west-2
      ecr_repository: null
      ecr_auto_create: true
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: false
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: 1f95fc68-68c2-4eef-a4ac-e68037de01a4
    authorizer_configuration: null
    oauth_configuration:
      workload_name: workload-df649d6a
  st02:
    name: st02
    entrypoint: strands_agents_streaming.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::266239926753:role/agentcorerole
      account: '266239926753'
      region: us-west-2
      ecr_repository: null
      ecr_auto_create: true
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: f20c626b-5ff7-47de-a4d3-c047594564d9
    authorizer_configuration: null
    oauth_configuration:
      workload_name: workload-fe560d1f
